"""
Google OAuth Setup - One-time refresh token generator for Google Sheets, Drive & Calendar API.

This script performs the OAuth 2.0 authorization flow to obtain a refresh token
that enables the application to access Google Sheets, Drive, and Calendar without user interaction.

Prerequisites:
    1. Download OAuth client credentials from Google Cloud Console
       (APIs & Services > Credentials > OAuth 2.0 Client IDs)
    2. Save as 'google_sheets.json' in the project root
    3. Install: pip install google-auth-oauthlib

Usage:
    python services/google_oauth_setup.py

What happens:
    1. Opens a browser window for Google sign-in
    2. Requests permission to access Google Sheets, Google Drive, and Google Calendar
    3. Captures the authorization code via local redirect
    4. Exchanges it for access + refresh tokens
    5. Prints the refresh token to add to .env

After running:
    Credentials are saved to: tmp/google_oauth_credentials.env
    Copy the values from that file to your .env file.
    Delete the temp file after copying for security.

Note:
    The refresh token is long-lived and only needs to be generated once.
    It will be used to automatically obtain new access tokens as needed.
"""
from pathlib import Path
from google_auth_oauthlib.flow import InstalledAppFlow

SCOPES = [
    'https://www.googleapis.com/auth/spreadsheets',
    'https://www.googleapis.com/auth/drive.readonly',  # Read all Drive files (was drive.file - app-created only)
    'https://www.googleapis.com/auth/drive.file',      # Write files created by app
    'https://www.googleapis.com/auth/calendar',
]
PROJECT_ROOT = Path(__file__).parent.parent.parent


def main():
    """Run OAuth flow and print refresh token for .env configuration."""
    credentials_file = Path(__file__).parent / 'google_auth.json'

    if not credentials_file.exists():
        print(f"ERROR: {credentials_file.name} not found in {credentials_file.parent}")
        print("Download OAuth client credentials from Google Cloud Console.")
        print("(APIs & Services > Credentials > OAuth 2.0 Client IDs)")
        print(f"Save it as: {credentials_file}")
        return

    flow = InstalledAppFlow.from_client_secrets_file(
        credentials_file,
        scopes=SCOPES
    )

    # Run local server to handle OAuth callback
    credentials = flow.run_local_server(port=8080)

    # Write credentials to temp file for safe transfer to .env
    output_file = PROJECT_ROOT / "tmp" / "google_oauth_credentials.env"
    output_file.parent.mkdir(exist_ok=True)

    env_content = f"""# Google OAuth Credentials - Generated by google_oauth_setup.py
# Copy these values to your .env file

GOOGLE_REFRESH_TOKEN={credentials.refresh_token}
GOOGLE_CLIENT_ID={credentials.client_id}
GOOGLE_CLIENT_SECRET={credentials.client_secret}

# Also add your Google Sheet ID and Drive folder ID:
# PAYCHECK_SHEET_ID=<your_sheet_id>
# PAYCHECK_FOLDER_ID=<your_folder_id>
"""

    output_file.write_text(env_content)

    print("\n" + "=" * 60)
    print("SUCCESS! Credentials saved to:")
    print(f"  {output_file}")
    print("=" * 60)
    print("\nCopy the values from that file to your .env file.")
    print("Delete the temp file after copying for security.")
    print("=" * 60)


if __name__ == "__main__":
    main()
